version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    env_file:
      - 'docs/prometheus/env.grafana'
    depends_on:
      - prometheus
#    volumes:
#      # Data persistency
#      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
#      - ./data/graphana:/var/lib/grafana
  url-shortener:
    image: url-shortener:latest
    command:
      - "startserver"
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    environment:
      HTTPSERVER_PORT: 8080
      DATABASE_HOSTNAME: host.docker.internal
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root@123
      DATABASE_DATABASENAME: short_url

