// Code generated by mockery v2.13.1. DO NOT EDIT.

package shorturl

import mock "github.com/stretchr/testify/mock"

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *MockService) Create(_a0 CreateRequest) (ShortURL, error) {
	ret := _m.Called(_a0)

	var r0 ShortURL
	if rf, ok := ret.Get(0).(func(CreateRequest) ShortURL); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(ShortURL)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(CreateRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockService(t mockConstructorTestingTNewMockService) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
