// Code generated by mockery v2.14.0. DO NOT EDIT.

package shorturl

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCore is an autogenerated mock type for the Core type
type MockCore struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockCore) Create(ctx context.Context, req CreateRequest) (ShortURL, error) {
	ret := _m.Called(ctx, req)

	var r0 ShortURL
	if rf, ok := ret.Get(0).(func(context.Context, CreateRequest) ShortURL); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(ShortURL)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, CreateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, shortURLPath
func (_m *MockCore) Get(ctx context.Context, shortURLPath string) (ShortURL, error) {
	ret := _m.Called(ctx, shortURLPath)

	var r0 ShortURL
	if rf, ok := ret.Get(0).(func(context.Context, string) ShortURL); ok {
		r0 = rf(ctx, shortURLPath)
	} else {
		r0 = ret.Get(0).(ShortURL)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortURLPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockCore interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockCore creates a new instance of MockCore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockCore(t mockConstructorTestingTNewMockCore) *MockCore {
	mock := &MockCore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
